spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/camping?serverTimezone=Asia/Seoul
    username: camping
    password: 1234
mybatis:
  configuration:
    map-underscore-to-camel-case: true
