spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camping?serverTimezone=Asia/Seoul
    username: camping
    password: 1234
mybatis:
  configuration:
    map-underscore-to-camel-case: true
